on: 
  push:
  pull_request:

name: Build

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.5", "5.4", "5.3"]

    steps:
    - uses: actions/checkout@v2.3.5

    - uses:  marcprux/setup-swift@a990bc57c514a77d232b645843ade099af21aa5e
      with:
        swift-version: ${{ matrix.swift }}

    - run: swift --version

    - run: swift build

    - run: swift test --enable-test-discovery
