name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

    - name: Generate Docs
      uses: sersoft-gmbh/swifty-docs-action@v3.1.0
      with:
        output: docs
        clean: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
    
