name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2.4.0

    - name: Generate Docs
      uses: sersoft-gmbh/swifty-docs-action@v1.2.1
      with:
        output: docs
        clean: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
    
