name: Publish Documentation

on:
  workflow_dispatch:
  push:
    branches:
    - main
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

    - name: Generate Docs
      uses: sersoft-gmbh/swifty-docs-action@v3.0.0
      with:
        output: docs
        clean: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
    
