
name: Renovate

on:
  schedule:
  - cron: '0/5 * * * *'
  push:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
        with:
          fetch-depth: 0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.3.1
        with:
          configurationFile: .github/renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
