
name: Renovate

on:
  schedule:
  - cron: '0/5 * * * *'
  push:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          fetch-depth: 0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          configurationFile: .github/renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
